spring:
  profiles: local

  datasource :
    hikari:
      #      driver-class-name: org.h2.Driver
      #      jdbc-url: jdbc:h2:mem:nftgram;DB_CLOSE_DELAY=-1
      #      username: sa
      #      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/nftgram;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: nftbatch
      password: "!vhdkdnj1234"

  jpa:
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

    hibernate:
      ddl-auto: none
    #      ddl-auto: create

    database-platform: org.hibernate.dialect.MySQL8Dialect
    #    database-platform: org.hibernate.dialect.H2Dialect
    #    database-platform: H2
    open-in-view: false
    generate-ddl: false
    database: mysql

  h2:
    console:
      enabled: false
#      path: /h2-console