spring:


  datasource :
    hikari:
      driver-class-name: org.h2.Driver
#      jdbc-url: jdbc:h2:mem:testdb;
      url: jdbc:h2:tcp://localhost/~/testdb
      username: sa
      password:

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

    hibernate:
      ddl-auto: create

    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: true

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    cache: false

logging:
  level:
    com:
      staby: debug
    org:
      springframework:
        boot:
          autoconfigure: INFO
      hibernate:
        SQL: debug
#  profiles: local

nftgram:
  cookie:
    key: NftMember
    domainName: www-local.nftgram.io
  aes256:
    secretKey:

resurrection:
  access_token: 12000000
  refresh_token: 604800000
  secret_key: secretkey


opensea:
  api_url: https://api.opensea.io/api/v1
  opensea_contract_address: "0x495f947276749ce646f68ac8c248420045cb7b5e"
  stpl_contract_address: "0x4da1c8fa0c73f65e3854c1b42d85acbb336dda1e"
  wallet_master_id: "25543b82b9fe96223bd903b7037aab9d"
  assets_uri: "/assets"
  bundles_uri: "/bundles"
  single_asset_uri: "/asset/"
  single_contract_uri: "/asset_contract/"
  events_uri: "/events"
  collections_uri: "/collections"
