spring:
  profiles: local


  datasource :
    hikari:
      #            driver-class-name: org.h2.Driver
      #            jdbc-url: jdbc:h2:~/test;AUTO_SERVER=true
      #            jdbc-url: jdbc:h2:tcp://localhost/~/testdb;AUTO_SERVER=true
      #            username: sa
      #            password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: testbeddev
      password: "xptmxmqpem12!@"
      jdbc-url: jdbc:mysql://13.125.12.108:3306/testbed?serverTimezone=Asia/Seoul
      #      jdbc-url: jdbc:mysql://13.209.158.179:3306/nftgram?serverTimezone=Asia/Seoul
      maximum-pool-size: 51
      data-source-properties.cachePrepStmts: true
      data-source-properties.prepStmtCacheSize: 250
      data-source-properties.prepStmtCacheSqlLimit: 2048
      data-source-properties.useServerPrepStmts: true
      connection-timeout: 10000 #(10s)
      validation-timeout: 10000 #(10s)
      idle-timeout: 10000 #(10s)
      max-lifetime: 580000

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    hibernate:
#      ddl-auto: none
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #    database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: H2
    open-in-view: false
    generate-ddl: false

#    h2:
#      console:
#        enabled: true
#        path: /h2-console

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: false
    suffix: .html
    cache: false

logging:
  level:
    com:
      nftgram: trace
    org:
      springframework:
        #        security: debug
        boot:
          autoconfigure: trace
      hibernate:
        SQL: debug
        type: trace
#  profiles: local

testbed:
  api_url: https://openapi.openbanking.or.kr/v2.0/
  client_id: b13d9333-727a-4644-8392-02eef0c39359
  client_secret: 9de6108f-fc49-4721-b232-1aad11096204
  oauth: /oauth/
  cookie:
    key: local.finger.run
    domainName: local.finger.run
    #    domainName: edac-14-52-144-35.ngrok.io
    aes256:
      secretKey: 3021ACABD914C42D80C4E9D2D1BBA293