spring:
  profiles: prod

  datasource :
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: testbeddev
      password: "xptmxmqpem12!@"
      jdbc-url: jdbc:mysql://13.125.12.108:3306/testbed?serverTimezone=Asia/Seoul
      maximum-pool-size: 51
      data-source-properties.cachePrepStmts: true
      data-source-properties.prepStmtCacheSize: 250
      data-source-properties.prepStmtCacheSqlLimit: 2048
      data-source-properties.useServerPrepStmts: true
      connection-timeout: 10000 #(10s)
      validation-timeout: 10000 #(10s)
      idle-timeout: 10000 #(10s)
      max-lifetime: 580000

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    cache: true

logging:
  level:
    com:
      testbed: info
    org:
      hibernate:
        SQL: info



testbed:
  api_url: https://openapi.openbanking.or.kr/v2.0/
  client_id: b13d9333-727a-4644-8392-02eef0c39359
  client_secret: 9de6108f-fc49-4721-b232-1aad11096204
  oauth: /oauth/