spring:
  profiles: prod

  datasource :
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: nftbatch
      password: "!vhdkdnj1234"
      jdbc-url: jdbc:mysql://127.0.0.1:3306/nftgram?serverTimezone=Asia/Seoul

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    cache: true

logging:
  level:
    com:
      nftgram: info
    org:
      hibernate:
        SQL: info


nftgram:
  cookie:
    key: admin.nftgram.ai
    domainName: admin.nftgram.ai
  aes256:
    secretKey: 3021ACABD914C42D80C4E9D2D1BBA293

# 프로퍼티 암호화 설정
#jasypt:
#  encryptor:
#    algorithm: PBEWithMD5AndDES
#    pool-size: 1
#    property:
#      prefix: ENC(
#      suffix: )
#    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
#    string-output-type: base64
#    provider-name: SunJCE
#    key-obtention-iterations: 1000



#web:
#  resources:
#    add-mappings: false

opensea:
  api_url: https://api.opensea.io/api/v1
  opensea_contract_address: "0x495f947276749ce646f68ac8c248420045cb7b5e"
  stpl_contract_address: "0x4da1c8fa0c73f65e3854c1b42d85acbb336dda1e"
  wallet_master_id: "25543b82b9fe96223bd903b7037aab9d"
  assets_uri: "/assets"
  bundles_uri: "/bundles"
  single_asset_uri: "/asset/"
  single_contract_uri: "/asset_contract/"
  events_uri: "/events"
  collections_uri: "/collections"